### ISSUE TITLE
Error: Expected parameter covariance_matrix of distribution MultivariateNormal to satisfy the constraint PositiveDefinite()

### ISSUE THREAD

**Issue by MultiTrickFox** [Lewis-Stuart-11/3DGS-to-PC#1]
Hi, I get the following error in my case. The photos were done sequentially, and mapped with colmap sequential. And the gaussian was produced with no errors either.

```
Loading Gaussians from File
Rendering Gaussian Colours
100% 306/306 [06:53<00:00,  1.35s/it]

Distributed Points to Gaussians

Starting Point Cloud Generation
 78% 131/167 [00:03<00:00, 41.89it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/Stuff/Splats/3DGS-to-PC/gauss_to_pc.py", line 437, in <module>
    main()
  File "/content/drive/MyDrive/Stuff/Splats/3DGS-to-PC/gauss_to_pc.py", line 426, in main
    total_points, total_colours = generate_pointcloud(args.input_path, args.num_points, std_distance=args.std_distance, render_colours=not args.skip_render_colours,
  File "/content/drive/MyDrive/Stuff/Splats/3DGS-to-PC/gauss_to_pc.py", line 344, in generate_pointcloud
    new_points, new_colours = create_new_gaussian_points(num_points_for_gaussian-1, mean_for_point, covariances_for_point,
  File "/content/drive/MyDrive/Stuff/Splats/3DGS-to-PC/gauss_to_pc.py", line 130, in create_new_gaussian_points
    original_sampled_points = MultivariateNormal(new_means_for_point, new_covariances_for_point).sample((num_points_to_sample,))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributions/multivariate_normal.py", line 180, in __init__
    super().__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributions/distribution.py", line 71, in __init__
    raise ValueError(
ValueError: Expected parameter covariance_matrix (Tensor of shape (4, 3, 3)) of distribution MultivariateNormal(loc: torch.Size([4, 3]), covariance_matrix: torch.Size([4, 3, 3])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[[  3.2363,  12.9381,   4.1813],
         [ 12.9381,  51.8894,  16.8407],
         [  4.1813,  16.8407,   5.4975]],

        [[  7.6815,   3.0631,  -4.8428],
         [  3.0631,   3.9977,  -7.8370],
         [ -4.8428,  -7.8370,  18.6801]],

        [[ 39.1303, -14.0143, -28.1381],
         [-14.0143,   5.0191,  10.0775],
         [-28.1381,  10.0775,  20.2338]],

        [[ 14.6058,   9.5375,  -0.8365],
         [  9.5375,  12.5323,  -0.5761],
         [ -0.8365,  -0.5761,   1.5277]]], device='cuda:0')

```

**Comment by Lewis-Stuart-11** [comment]
Thanks for raising this

It seems that some of the Gaussians that are being loaded in are not positive definite. I've improved the regularisation process in the Gaussian Handler to ensure that all Gaussian covariance matrices will work correctly. If you try again with the latest commit it should hopefully convert to a point cloud fine. Let me know if it doesn't

**Comment by MultiTrickFox** [comment]
Hey! it has been a few days I looked into the issue and went through some methods to fix it..

I read your code, and if i'm not mistaken you're now doing the jitter method of adding small positive values.
I have put together possible methods to best fix it (best in order) - please take a look at it and let me know what you think about the approaches.. Do you think their priorities should be different or they're good in order?

```
def make_positive_definite(cov_matrix, min_eigenvalue=1e-5):

    # Enforce symmetry
    cov_matrix = (cov_matrix + cov_matrix.transpose(-1, -2)) / 2

    # Try Eigenvalue Clipping
    try:
        eigvals, eigvecs = torch.linalg.eigh(cov_matrix)
        eigvals = torch.clamp(eigvals, min=min_eigenvalue)
        cov_matrix = eigvecs @ torch.diag_embed(eigvals) @ eigvecs.transpose(-1, -2)
        eig_vals = torch.linalg.eigvalsh(cov_matrix)
        if torch.all(eig_vals > 0):
            return cov_matrix
    except Exception:
        pass

    # Try Softplus on Diagonal
    try:
        diag_indices = torch.arange(cov_matrix.size(-1), device=cov_matrix.device)
        cov_matrix[..., diag_indices, diag_indices] = torch.nn.functional.softplus(cov_matrix[..., diag_indices, diag_indices])
        eig_vals = torch.linalg.eigvalsh(cov_matrix)
        if torch.all(eig_vals > 0):
            return cov_matrix
    except Exception:
        pass

    # Try Cholesky Reparameterization
    try:
        jitter = min_eigenvalue
        cov_matrix += torch.eye(cov_matrix.size(-1), device=cov_matrix.device) * jitter
        L = torch.linalg.cholesky(cov_matrix)
        cov_matrix = L @ L.transpose(-1, -2)
        return cov_matrix
    except RuntimeError:
        pass

    # Try Jitter as a last resort
    jitter = min_eigenvalue
    cov_matrix += torch.eye(cov_matrix.size(-1), device=cov_matrix.device) * jitter
    eig_vals = torch.linalg.eigvalsh(cov_matrix)
    assert torch.all(eig_vals > 0), "Covariance matrices are still not positive definite after applying all methods."
    return cov_matrix
```

**Comment by Lewis-Stuart-11** [comment]
Thanks for this, I appreciate the effort.

The eigen clipping method is probably the most effective solution here, so I have added this to the main branch along with the initial jittering approach. Cheers!
I've not included the rest; the clipping approach should do the trick on its own. Any covariances matrices that are still not positive-definite after this should really be removed, as they are most likely erroneous (chances of this are very low anyway). I've added some code to delete any unwanted Gaussians. Let me know if that doesn't work

**Comment by nishanth-scanbox** [comment]
Hello,

Firstly thanks for the code and it is really helpful. Could you help me out on this issue please? I am getting the same error message what @MultiTrickFox was facing on. I copied the log below for reference. I would be glad if sme1 helps me out.

Thanks in advance.

Traceback (most recent call last):
  File "gauss_to_pc.py", line 649, in <module>
    main()
  File "gauss_to_pc.py", line 608, in main
    total_point_cloud, surface_point_cloud = convert_3dgs_to_pc(args.input_path, args.transform_path, pointcloud_settings)
  File "gauss_to_pc.py", line 453, in convert_3dgs_to_pc
    num_sample_attempts=num_sample_attempts)
  File "gauss_to_pc.py", line 331, in generate_pointcloud
    normals=normals_for_point, device=device)
  File "gauss_to_pc.py", line 181, in create_new_gaussian_points
    original_sampled_points = MultivariateNormal(new_means_for_point, new_covariances_for_point).sample((num_points_to_sample,))
  File "C:\Users\sbx\.conda\envs\gaussian_splatting\lib\site-packages\torch\distributions\multivariate_normal.py", line 146, in __init__
    super(MultivariateNormal, self).__init__(batch_shape, event_shape, validate_args=validate_args)
  File "C:\Users\sbx\.conda\envs\gaussian_splatting\lib\site-packages\torch\distributions\distribution.py", line 56, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter covariance_matrix (Tensor of shape (2, 3, 3)) of distribution MultivariateNormal(loc: torch.Size([2, 3]), covariance_matrix: torch.Size([2, 3, 3])) to satisfy the constraint PositiveDefinite(), but found invalid values:
tensor([[[ 0.2486, -4.2609,  0.4615],
         [-4.2609, 77.5503, -8.4535],
         [ 0.4615, -8.4535,  0.9221]],

        [[17.9395,  4.5693, 33.1697],
         [ 4.5693,  1.1638,  8.4486],
         [33.1697,  8.4486, 61.3298]]], device='cuda:0')
