### ISSUE TITLE
Inquiry about Related Documents or Papers on Methodology

### ISSUE THREAD

**Issue by kai0416s** [Lewis-Stuart-11/3DGS-to-PC#2]
Hi, thank you for the outstanding work.
I’d like to ask if there are any related documents or papers available on your methodology, or is this simply a library that you provide?

Thank you, looking forward to your response.

Best regards,
Kai

**Comment by Lewis-Stuart-11** [comment]
Hi Kai,

Thank you, that's very kind. 

I've included a basic overview on the README about how this all works, but it is very brief. Currently, I don't have any papers/documents written about this framework, but I'm planning on writing a paper about this soon. I will let you know when I get something published.

Cheers,
Lewis

**Comment by Lewis-Stuart-11** [comment]
Hi Kai,

Just letting you know that I have published a paper about this framework that can be found using this link: https://arxiv.org/abs/2501.07478

Thank you
